const Constant = {
  ID: "ID",
  FULLNAME: "FULLNAME",
  EMAIL: "EMAIL",
  ROLE: "ROLE",
  TOKEN: "TOKEN",
  REFRESH_TOKEN: "REFRESH_TOKEN",

  ROLE_ADMIN: "ADMIN",
  ROLE_MANAGER: "MANAGER",
  ROLE_TEACHER: "TEACHER",
  ROLE_STUDENT: "STUDENT",
}